#!/usr/bin/env python3
"""Generate domain-cards-data.js from structured card definitions."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

DOMAINS = {
    "deep": {
        "name": "Deep",
        "glyph": "∞",
        "was": "Arcana",
        "tagline": "Xenoarchaeology, alien biology, ancient technologies, void phenomena, and lore from dead civilizations.",
        "terminology": [
            "Hope → Signal",
            "Spellcast Roll → Channel Roll",
            "Spellcast trait → Channel trait",
            "magic damage → energy damage",
            "On Fire → Ignited",
            "Arcana Spell → Deep Spell",
            "Arcana Ability → Deep Ability",
        ],
    },
    "iron": {
        "name": "Iron",
        "glyph": "⛨",
        "was": "Blade",
        "tagline": "Direct combat, personal weapons, armor use, close-quarters tactics, and refusing to go down.",
        "terminology": [
            "Hope → Signal",
            "Fear → Static",
            "Spellcast Roll → Channel Roll",
            "Blade Ability → Iron Ability",
            "weapon covers both kinetic and powered weapons in Voidheart",
        ],
    },
    "vector": {
        "name": "Vector",
        "glyph": "↗",
        "was": "Bone",
        "tagline": "Ship piloting, jump navigation, evasive maneuvers, orbital mechanics, and reading space like a language.",
        "terminology": [
            "Hope → Signal",
            "Fear → Static",
            "Spellcast Roll → Channel Roll",
            "Bone Ability → Vector Ability",
            "weapon covers both kinetic and powered weapons in Voidheart",
        ],
    },
    "grid": {
        "name": "Grid",
        "glyph": "⊞",
        "was": "Codex",
        "tagline": "Hacking, electronic warfare, system intrusion, drone control, and the weaponization of information.",
        "terminology": [
            "Hope → Signal",
            "Fear → Static",
            "Spellcast Roll → Channel Roll",
            "Spellcast trait → Channel trait",
            "magic damage → energy damage",
            "Codex Spell → Grid Spell",
            "Codex Ability → Grid Ability",
            "Codex Grimoire → Grid Archive",
            '"Book of X" → "Archive of X"',
        ],
    },
    "sable": {
        "name": "Sable",
        "glyph": "◆",
        "was": "Grace",
        "tagline": "Smuggling, underworld contacts, improvised solutions, heists, and the charisma of someone with nothing to lose.",
        "terminology": [
            "Hope → Signal",
            "Fear → Static",
            "Spellcast Roll → Channel Roll",
            "Spellcast trait → Channel trait",
            "Grace Spell → Sable Spell",
            "Grace Ability → Sable Ability",
        ],
    },
    "shadow": {
        "name": "Shadow",
        "glyph": "◐",
        "was": "Midnight",
        "tagline": "Stealth, infiltration, disguise, assassination, and moving through places you were never supposed to be.",
        "terminology": [
            "Hope → Signal",
            "Fear → Static",
            "Spellcast Roll → Channel Roll",
            "Spellcast trait → Channel trait",
            "magic damage → energy damage",
            "can't cast spells → can't use Channel abilities",
            "Midnight Spell/Ability → Shadow Spell/Ability",
        ],
    },
    "cipher": {
        "name": "Cipher",
        "glyph": "⌬",
        "was": "Sage",
        "tagline": "Science, medicine, engineering, analysis, and building things no one else could from what's at hand.",
        "terminology": [
            "Hope → Signal",
            "Fear → Static",
            "Spellcast Roll → Channel Roll",
            "Spellcast trait → Channel trait",
            "magic damage → energy damage",
            "Sage Spell → Cipher Spell",
            "Sage Ability → Cipher Ability",
        ],
    },
    "psionic": {
        "name": "Psionic",
        "glyph": "✺",
        "was": "Splendor",
        "tagline": "Mental projection, emotional reading, precognition, psychic defense, and communion with the inhuman.",
        "terminology": [
            "Hope → Signal",
            "Fear → Static",
            "Spellcast Roll → Channel Roll",
            "Spellcast trait → Channel trait",
            "magic damage → psionic damage",
            "Splendor Spell → Psionic Spell",
            "Splendor Ability → Psionic Ability",
        ],
    },
    "tide": {
        "name": "Tide",
        "glyph": "≈",
        "was": "Valor",
        "tagline": "Leadership, morale, tactical coordination, inspiring under fire, and the weight of being the one others follow.",
        "terminology": [
            "Hope → Signal",
            "Fear → Static",
            "Valor Ability → Tide Ability",
        ],
    },
}

# (domain, name, was, level, type, recall, effect)
CARDS = [
    # DEEP
    ("deep", "Ward Glyph", "Rune Ward", 1, "spell", 0,
     "You have a deeply personal artifact—a precursor sigil etched into your gear, a salvaged token from a dead civilization, or a fragment of alien ore—that can be infused with protective void energy as a ward by you or an ally. Describe what it is and why it's important to you. The ward's bearer can spend a Signal to reduce incoming damage by 1d8. If the Ward Die result is 8, the ward's power ends after it reduces damage this turn. It can be recharged for free on your next rest."),
    ("deep", "Void Surge", "Unleash Chaos", 1, "spell", 1,
     "At the beginning of a session, place a number of tokens equal to your Channel trait on this card. Make a Channel Roll against a target within Far range and spend any number of tokens to channel raw void energy from within yourself to unleash against them. On a success, roll a number of d10s equal to the tokens you spent and deal that much energy damage to the target. Mark a Stress to replenish this card with tokens (up to your Channel trait). At the end of each session, clear all unspent tokens."),
    ("deep", "Drift Walk", "Wall Walk", 1, "spell", 1,
     "Spend a Signal to allow a creature you can touch to manipulate local gravity, walking on walls and ceilings as easily as walking on the ground. This lasts until the end of the scene or you cast Drift Walk again."),
    ("deep", "Plasma Grasp", "Cinder Grasp", 2, "spell", 1,
     "Make a Channel Roll against a target within Melee range. On a success, the target instantly bursts into superheated plasma, takes 1d20+3 energy damage, and is temporarily Ignited. When a creature acts while Ignited, they must take an extra 2d6 energy damage if they are still Ignited at the end of their action."),
    ("deep", "Drift Eye", "Floating Eye", 2, "spell", 0,
     "Spend a Signal to create a single, small drifting orb of contained void energy that you can move anywhere within Very Far range. While this orb is active, you can see through it as though you were looking out from its position. You can transition between using your own senses and seeing through the orb freely. If the orb takes damage or moves out of range, the spell ends."),
    ("deep", "Null Field", "Counterspell", 3, "spell", 2,
     "You can interrupt a void, psionic, or technological effect taking place by making a reaction roll using your Channel trait. On a success, the effect stops and any consequences are avoided, and this card is placed in your vault."),
    ("deep", "Voidflight", "Flight", 3, "spell", 1,
     "Make a Channel Roll (15). On a success, place a number of tokens equal to your Agility on this card (minimum 1). You can fly freely while tokens remain on this card. When you make an action roll while flying, spend a token from this card. After the action that spends the last token is resolved, you descend gently to the ground directly below you."),
    ("deep", "Blink Shift", "Blink Out", 4, "spell", 1,
     "Make a Channel Roll (12). On a success, spend a Signal to fold space and instantly shift to another point you can see within Far range. If any willing creatures are within Very Close range, spend an additional Signal for each creature to bring them with you."),
    ("deep", "Repulsion Wave", "Preservation Blast", 4, "spell", 1,
     "Make a Channel Roll against all targets within Melee range. Targets you succeed against are forced back to Far range and take d8+3 energy damage using your Channel trait."),
    ("deep", "Arc Cascade", "Chain Lightning", 5, "spell", 1,
     "Mark 2 Stress to make a Channel Roll, unleashing arcing plasma on all targets within Close range. Targets you succeed against must make a reaction roll with a Difficulty equal to the result of your Channel Roll. Targets who fail take 2d8+4 energy damage. Additional adversaries not already targeted by Arc Cascade and within Close range of previous targets who took damage must also make the reaction roll. Targets who fail take 2d8+4 energy damage. This chain continues until there are no more adversaries within range."),
    ("deep", "Precognition", "Premonition", 5, "spell", 2,
     "You can channel void energy to glimpse moments not yet collapsed into reality. Once per long rest, immediately after the GM conveys the consequences of a roll you made, you can rescind the move and consequences like they never happened and make another move instead."),
    ("deep", "Rift Walker", None, 6, "spell", 2,
     "Make a Channel Roll (15). On a success, you place a void anchor on the ground where you currently stand. The next time you successfully cast Fold Anchor, a rift in space opens up, providing safe passage back to the exact spot where the first anchor was placed. This rift stays open until you choose to close it or you cast another spell. You can drop the spell at any time to cast Fold Anchor again and place the anchor somewhere new."),
    ("deep", "Graviton Grip", "Telekinesis", 6, "spell", 0,
     "Make a Channel Roll against a target within Far range. On a success, you can use focused graviton manipulation to move them anywhere within Far range of their original position. You can throw the lifted target as an attack by making an additional Channel Roll against the second target you're trying to attack. On a success, deal d12+4 physical damage to the second target using your Proficiency. This spell then ends."),
    ("deep", "Void-Touched", "Arcana-Touched", 7, "ability", 2,
     "When 4 or more of the domain cards in your loadout are from the Deep domain, gain the following benefits: +1 bonus to your Channel Rolls; once per rest, you can switch the results of your Signal and Static Dice."),
    ("deep", "Refraction Cloak", "Cloaking Blast", 7, "spell", 2,
     "When you make a successful Channel Roll to cast a different spell, you can spend a Signal to bend light around your body and become Cloaked. While Cloaked, you remain unseen if you are stationary when an adversary moves to where they would normally see you. When you move into or within an adversary's line of sight or make an attack, you are no longer Cloaked."),
    ("deep", "Void Mirror", "Arcane Reflection", 8, "spell", 1,
     "When you would take energy damage, you can spend any number of Signal to roll that many d6s. If any roll a 6, the attack is reflected back to the caster, dealing the damage to them instead."),
    ("deep", "Phantom Layers", "Confusing Aura", 8, "spell", 1,
     "Make a Channel Roll (14). Once per long rest on a success, you create a layer of holographic projection over your body that makes it hard to tell exactly where you are. Mark any number of Stress to make that many additional layers. When an adversary makes an attack against you, roll a number of d6s equal to the number of layers currently active. If any roll a 5 or higher, one layer is destroyed and the attack fails. If all results are 4 or lower, you take the damage and this spell ends."),
    ("deep", "Gravitic Shockwave", "Earthquake", 9, "spell", 2,
     "Make a Channel Roll (16). Once per rest on a success, all targets within Very Far range who aren't flying must make a Reaction Roll (18). Targets who fail take 3d10+8 physical damage and are temporarily Vulnerable. Targets who succeed take half damage. Additionally, when you succeed on the Channel Roll, all terrain within Very Far range becomes difficult to move through and structures within this range might sustain damage or crumble."),
    ("deep", "Sensory Projection", None, 9, "spell", 0,
     "Once per rest, make a Channel Roll (15). On a success, drop into a remote-viewing trance that lets you clearly see and hear any place you have been before as though you are standing there in this moment. You can move freely in this projection and are not constrained by the physics or impediments of a physical body. This projection cannot be detected by mundane or technological means. You drop out of it upon taking damage or casting another spell."),
    ("deep", "Adjust Reality", None, 10, "spell", 1,
     "After you or a willing ally make any roll, you can spend 5 Signal to change the numerical result of that roll to a result of your choice instead. The result must be plausible within the range of the dice."),
    ("deep", "Starfall", "Falling Sky", 10, "spell", 1,
     "Make a Channel Roll against all adversaries within Far range. Mark any number of Stress to call down shards of void debris and ancient orbital wreckage from above. Targets you succeed against take 1d20+2 energy damage for each Stress marked."),
    # IRON
    ("iron", "Get Back Up", None, 1, "ability", 1,
     "When you take Severe damage, you can mark a Stress to reduce the severity by one threshold."),
    ("iron", "Not Good Enough", None, 1, "ability", 1,
     "When you roll your damage dice, you can reroll any 1s or 2s."),
    ("iron", "Whirlwind", None, 1, "ability", 0,
     "When you make a successful attack against a target within Very Close range, you can spend a Signal to use the attack against all other targets within Very Close range. All additional adversaries you succeed against with this ability take half damage."),
    ("iron", "A Soldier's Bond", None, 2, "ability", 1,
     "Once per long rest, when you compliment someone or ask them about something they're good at, you can both gain 3 Signal."),
    ("iron", "Reckless", None, 2, "ability", 1,
     "Mark a Stress to gain advantage on an attack."),
    ("iron", "Scramble", None, 3, "ability", 1,
     "Once per rest, when a creature within Melee range would deal damage to you, you can avoid the attack and safely move out of Melee range of the enemy."),
    ("iron", "Versatile Fighter", None, 3, "ability", 1,
     "You can use a different character trait for an equipped weapon, rather than the trait the weapon calls for. When you deal damage, you can mark a Stress to use the maximum result of one of your damage dice instead of rolling it."),
    ("iron", "Deadly Focus", None, 4, "ability", 2,
     "Once per rest, you can apply all your focus toward a target of your choice. Until you attack another creature, you defeat the target, or the battle ends, gain a +1 bonus to your Proficiency."),
    ("iron", "Fortified Armor", None, 4, "ability", 0,
     "While you're wearing armor, gain a +2 bonus to your damage thresholds."),
    ("iron", "Champion's Edge", None, 5, "ability", 1,
     "When you critically succeed on an attack, you can spend up to 3 Signal and choose one of the following options for each Signal spent: you clear a Hit Point; you clear an Armor Slot; the target must mark an additional Hit Point. You can't choose the same option more than once."),
    ("iron", "Vitality", None, 5, "ability", 0,
     "When you choose this card, permanently gain two of the following benefits: one Stress slot; one Hit Point slot; +2 bonus to your damage thresholds. Then place this card in your vault permanently."),
    ("iron", "Battle-Hardened", None, 6, "ability", 2,
     "Once per long rest when you would make a Death Move, you can spend a Signal to clear a Hit Point instead."),
    ("iron", "Rage Up", None, 6, "ability", 1,
     "Before you make an attack, you can mark a Stress to gain a bonus to your damage roll equal to twice your Strength. You can Rage Up twice per attack."),
    ("iron", "Iron-Touched", "Blade-Touched", 7, "ability", 1,
     "When 4 or more of the domain cards in your loadout are from the Iron domain, gain the following benefits: +2 bonus to your attack rolls; +4 bonus to your Severe damage threshold."),
    ("iron", "Glancing Blow", None, 7, "ability", 1,
     "When you fail an attack, you can mark a Stress to deal weapon damage using half your Proficiency."),
    ("iron", "Battle Cry", None, 8, "ability", 2,
     "Once per long rest, while you're charging into danger, you can muster a rousing call that inspires your allies. All allies who can hear you each clear a Stress and gain a Signal. Additionally, your allies gain advantage on attack rolls until you or an ally rolls with Static."),
    ("iron", "Frenzy", None, 8, "ability", 3,
     "Once per long rest, you can go into a Frenzy until there are no more adversaries within sight. While Frenzied, you can't use Armor Slots, and you gain a +10 bonus to your damage rolls and a +8 bonus to your Severe damage threshold."),
    ("iron", "Gore and Glory", None, 9, "ability", 2,
     "When you critically succeed on a weapon attack, gain an additional Signal or clear an additional Stress. Additionally, when you deal enough damage to defeat an enemy, gain a Signal or clear a Stress."),
    ("iron", "Reaper's Strike", None, 9, "ability", 3,
     "Once per long rest, spend a Signal to make an attack roll. The GM tells you which targets within range it would succeed against. Choose one of these targets and force them to mark 5 Hit Points."),
    ("iron", "Battle Monster", None, 10, "ability", 0,
     "When you make a successful attack against an adversary, you can mark 4 Stress to force the target to mark a number of Hit Points equal to the number of Hit Points you currently have marked instead of rolling for damage."),
    ("iron", "Onslaught", None, 10, "ability", 1,
     "When you successfully make an attack with your weapon, you never deal damage beneath a target's Major damage threshold (the target always marks a minimum of 2 Hit Points). Additionally, when a creature within your weapon's range deals damage to an ally with an attack that doesn't include you, you can mark a Stress to force them to make a Reaction Roll (15). On a failure, the target must mark a Hit Point."),
    # VECTOR
    ("vector", "Deft Maneuvers", None, 1, "ability", 0,
     "Once per rest, mark a Stress to sprint anywhere within Far range without making an Agility Roll to get there. You read the lane before you take it. If you end this movement within Melee range of an adversary and immediately make an attack against them, gain a +1 bonus to the attack roll."),
    ("vector", "I See It Coming", None, 1, "ability", 1,
     "When you're targeted by an attack made from beyond Melee range, you can mark a Stress to roll a d4 and gain a bonus to your Evasion equal to the result against the attack. You saw the trajectory before they finished the squeeze."),
    ("vector", "Untouchable", None, 1, "ability", 1,
     "Gain a bonus to your Evasion equal to half your Agility."),
    ("vector", "Ferocity", None, 2, "ability", 2,
     "When you cause an adversary to mark 1 or more Hit Points, you can spend 2 Signal to increase your Evasion by the number of Hit Points they marked. This bonus lasts until after the next attack made against you."),
    ("vector", "Strategic Approach", None, 2, "ability", 1,
     "After a long rest, place a number of tokens equal to your Knowledge on this card (minimum 1). The first time you move within Close range of an adversary and make an attack against them, you can spend one token to choose one of: make the attack with advantage; clear a Stress on an ally within Melee range of the adversary; add a d8 to your damage roll. When you take a long rest, clear all unspent tokens."),
    ("vector", "Brace", None, 3, "ability", 1,
     "When you mark an Armor Slot to reduce incoming damage, you can mark a Stress to mark an additional Armor Slot. You angle into the hit."),
    ("vector", "Tactician", None, 3, "ability", 1,
     "When you Help an Ally, they can spend a Signal to add one of your Experiences to their roll alongside your advantage die. When making a Tag Team Roll, you can roll a d20 as your Signal Die."),
    ("vector", "Boost", None, 4, "ability", 1,
     "Mark a Stress to boost off a willing ally within Close range, vault into the air on mag-boots or a thruster pulse, and perform an aerial attack against a target within Far range. You have advantage on the attack, add a d10 to the damage roll, and end your move within Melee range of the target."),
    ("vector", "Redirect", None, 4, "ability", 1,
     "When an attack made against you from beyond Melee range fails, roll a number of d6s equal to your Proficiency. If any roll a 6, you can mark a Stress to redirect the attack to damage an adversary within Very Close range instead."),
    ("vector", "Know Thy Enemy", None, 5, "ability", 1,
     "When observing a creature, you can make an Instinct Roll against them. On a success, spend a Signal and ask the GM for one set of information: unmarked Hit Points and Stress; Difficulty and damage thresholds; tactics and standard attack damage dice; features and Experiences. Additionally, on a success, you can mark a Stress to remove a Static from the GM's Static pool."),
    ("vector", "Signature Move", None, 5, "ability", 1,
     "Name and describe your signature combat move. Once per rest, when you perform this signature move as part of an action you're taking, you can roll a d20 as your Signal Die. On a success, clear a Stress."),
    ("vector", "Rapid Riposte", None, 6, "ability", 0,
     "When an attack made against you from within Melee range fails, you can mark a Stress and seize the opportunity to deal the weapon damage of one of your active weapons to the attacker."),
    ("vector", "Recovery", None, 6, "ability", 1,
     "During a short rest, you can choose a long rest downtime move. You can spend a Signal to let an ally do the same."),
    ("vector", "Vector-Touched", "Bone-Touched", 7, "ability", 1,
     "When 4 or more of the domain cards in your loadout are from the Vector domain, gain the following benefits: +1 bonus to Agility; once per rest, you can spend 3 Signal to cause an attack that succeeded against you to fail instead."),
    ("vector", "Cruel Precision", None, 7, "ability", 1,
     "When you make a successful attack with a weapon, gain a bonus to your damage roll equal to either your Finesse or Agility."),
    ("vector", "Breaking Blow", None, 8, "ability", 3,
     "When you make a successful attack, you can mark a Stress to make the next successful attack against that same target deal an extra 2d12 damage."),
    ("vector", "Wrangle", None, 8, "ability", 1,
     "Make an Agility Roll against all targets within Close range. Spend a Signal to move targets you succeeded against, and any willing allies within Close range, to another point within Close range."),
    ("vector", "On the Brink", None, 9, "ability", 1,
     "When you have 2 or fewer Hit Points unmarked, you don't take Minor damage."),
    ("vector", "Splintering Strike", None, 9, "ability", 3,
     "Spend a Signal and make an attack against all adversaries within your weapon's range. Once per long rest, on a success against any targets, roll your weapon's damage and distribute that damage however you wish between the targets you succeeded against. Before you deal damage to each target, roll an additional damage die and add its result to the damage you deal to them."),
    ("vector", "Deathrun", None, 10, "ability", 1,
     "Spend 3 Signal to run a straight path through the battlefield to a point within Far range, making an attack against all adversaries within your weapon's range along that path. Choose the order in which you deal damage to the targets you succeeded against. For the first, roll your weapon damage with a +1 bonus to your Proficiency. Then remove a die from your damage roll and deal the remaining damage to the next target. Continue until you have no more damage dice or adversaries. You can't target the same adversary more than once per attack."),
    ("vector", "Swift Step", None, 10, "ability", 2,
     "When an attack made against you fails, clear a Stress. If you can't clear a Stress, gain a Signal."),
    # GRID
    ("grid", "Archive of Ava", "Book of Ava", 1, "archive", 2,
     "Kinetic Bolt (was Power Push): Make a Channel Roll against a target within Melee range. On a success, they're knocked back to Far range and take d10+2 energy damage using your Proficiency.\nTava's Lattice (was Tava's Armor): Spend a Signal to give a target you can touch a +1 bonus to their Armor Score until their next rest or you cast Tava's Lattice again.\nCryo Spike (was Ice Spike): Make a Channel Roll (12) to summon a large cryo spike within Far range. If used as a weapon, make the Channel Roll against the target's Difficulty instead. On a success, deal d6 physical damage using your Proficiency."),
    ("grid", "Archive of Illiat", "Book of Illiat", 1, "archive", 2,
     "Lull Routine (was Slumber): Make a Channel Roll against a target within Very Close range. On a success, they're Asleep until they take damage or the GM spends a Static on their turn to clear this condition.\nData Salvo (was Arcane Barrage): Once per rest, spend any number of Signal and fire data projectiles at a target within Close range. Roll a number of d6s equal to the Signal spent and deal that much energy damage.\nNeural Uplink (was Telepathy): Spend a Signal to open an encrypted line of mental communication with one target you can see until your next rest or you cast Neural Uplink again."),
    ("grid", "Archive of Tyfar", "Book of Tyfar", 1, "archive", 2,
     "Plasma Arc (was Wild Flame): Make a Channel Roll against up to three adversaries within Melee range. Targets you succeed against take 2d6 energy damage and must mark a Stress.\nDrone Hand (was Magic Hand): You remotely deploy a manipulator drone with the same size and strength as your own within Far range.\nParticle Cloud (was Mysterious Mist): Make a Channel Roll (13) to release a temporary thick cloud of particulate within Very Close range that heavily obscures the area."),
    ("grid", "Archive of Vagras", "Book of Vagras", 1, "archive", 2,
     "Cipher Lock (was Runic Lock): Make a Channel Roll (15) on an object you're touching that can close. Once per rest on a success, encrypt it so only creatures of your choice can open it.\nFold Door (was Arcane Door): When you have no adversaries within Close range, make a Channel Roll (13). On a success, spend a Signal to open a folded-space portal to a point within Far range you can see. It closes once a creature has passed through.\nScan Pulse (was Reveal): Make a Channel Roll. If anything is concealed by cloaking or signal-baffling tech within Close range, it is revealed."),
    ("grid", "Archive of Sitil", "Book of Sitil", 2, "archive", 2,
     "Holoskin (was Adjust Appearance): Project a holographic overlay across your appearance and clothing to avoid recognition.\nEcho Protocol (was Parallela): Spend 2 Signal to cast on yourself or an ally within Close range. The next time the target makes an attack, they can hit an additional target within range that their attack roll would succeed against.\nHologram (was Illusion): Make a Channel Roll (14). On a success, project a temporary visual hologram within Close range that lasts as long as you maintain focus."),
    ("grid", "Archive of Korvas", "Book of Korvas", 3, "archive", 2,
     "Antigrav Lift (was Levitation): Make a Channel Roll to temporarily lift a target you can see and move them within Close range of their original position.\nMemory Scrub (was Recant): Spend a Signal to force a target within Melee range to make a Reaction Roll (15). On a failure, they forget the last minute of your conversation.\nProximity Field (was Rune Circle): Mark a Stress to deploy a temporary mine field where you stand. Adversaries within Melee range, or who enter it, take 2d12+4 energy damage and are knocked back to Very Close range."),
    ("grid", "Archive of Norai", "Book of Norai", 3, "archive", 2,
     "Grav Tether (was Mystic Tether): Make a Channel Roll against a target within Far range. On a success, they're temporarily Restrained and must mark a Stress. Flying creatures are grounded and Restrained.\nThermite Round (was Fireball): Make a Channel Roll against a target within Far range. On a success, hurl an explosive payload. The target and all creatures within Very Close range must make a Reaction Roll (13). Targets who fail take d20+5 energy damage using your Proficiency. Targets who succeed take half damage."),
    ("grid", "Archive of Exota", "Book of Exota", 4, "archive", 3,
     "Override Protocol (was Repudiate): Interrupt a program, code-effect, or system intrusion with a reaction roll using your Channel trait. Once per rest on a success, the effect stops and consequences are avoided.\nCreate Construct: Spend a Signal to assemble scrap into an animated drone that obeys basic commands. Make a Channel Roll to command it. It shares your Evasion and traits; its attacks deal 2d10+3 physical damage. You can only maintain one drone at a time."),
    ("grid", "Archive of Grynn", "Book of Grynn", 4, "archive", 2,
     "Counter Routine (was Arcane Deflection): Once per long rest, spend a Signal to negate the damage of an attack targeting you or an ally within Very Close range.\nStasis Lock (was Time Lock): Make a Channel Roll against an object within Far range. That object freezes in time and space until your next rest.\nPlasma Wall (was Wall of Flame): Make a Channel Roll (15). On a success, deploy a temporary wall of containment-grade plasma between two points within Far range. Anything that passes through takes 4d10+3 energy damage."),
    ("grid", "Hard Light Barrier", "Manifest Wall", 5, "spell", 2,
     "Make a Channel Roll (15). Once per rest on a success, spend a Signal to project a temporary hard-light barrier between two points within Far range (up to 50 feet high, any angle). Creatures or objects in its path are shunted to a side of your choice. The barrier stays up until your next rest or you cast Hard Light Barrier again."),
    ("grid", "Beacon Jump", "Teleport", 5, "spell", 2,
     "Once per long rest, execute a short-range micro-jump for yourself and any number of willing targets within Close range to a place you've been before. Make a Channel Roll (16) with a bonus based on familiarity (+3 very well, +1 frequently, 0 infrequently, −2 once). On a success, you arrive where intended; on a failure, you arrive off course."),
    ("grid", "Exile Protocol", "Banish", 6, "spell", 2,
     "Make a Channel Roll against a target within Close range. On a success, roll d20s equal to your Channel trait. The target must make a reaction roll with Difficulty equal to your highest result. On a success, they mark a Stress but aren't exiled. Once per rest on a failure, they are exiled from this dimension. When the PCs roll with Static, the Difficulty gains −1 and the target makes another reaction roll to return."),
    ("grid", "Vengeance Tag", "Sigil of Retribution", 6, "spell", 2,
     "Tag an adversary within Close range. When the marked adversary deals damage to you or your allies, place a d8 on this card (up to your level). When you successfully attack the marked adversary, roll the dice on this card and add the total to your damage roll, then clear the dice. Ends when the adversary is defeated or you cast Vengeance Tag again."),
    ("grid", "Archive of Homet", "Book of Homet", 7, "archive", 0,
     "Pass Through: Make a Channel Roll (13). Once per rest on a success, you and all creatures touching you can phase through a wall or door within Close range.\nDrift Gate (was Plane Gate): Make a Channel Roll (14). Once per long rest on a success, open a gateway to a location in another dimension or void layer you've been to before. Lasts until your next rest."),
    ("grid", "Grid-Touched", "Codex-Touched", 7, "ability", 2,
     "When 4 or more of the domain cards in your loadout are from the Grid domain: you can mark a Stress to add your Proficiency to a Channel Roll; once per rest, replace this card with any card from your vault without paying its Recall Cost."),
    ("grid", "Archive of Vyola", "Book of Vyola", 8, "archive", 2,
     "Memory Probe (was Memory Delve): Make a Channel Roll against a target within Far range. On a success, jack into their neural buffer and ask the GM a question about their memories.\nShared Clarity: Once per long rest, spend a Signal to network two willing creatures. When one would mark Stress, they choose who marks it. Lasts until their next rest."),
    ("grid", "Safe Haven", None, 8, "spell", 3,
     "When you have a few minutes of calm, spend 2 Signal to summon your Safe Haven—a large folded-space refuge. A sealed doorway appears within Close range; only creatures of your choice can enter. Once inside, you can make the entrance invisible. When you take a rest within your own Safe Haven, you can choose an additional downtime move."),
    ("grid", "Archive of Ronin", "Book of Ronin", 9, "archive", 4,
     "Transform: Make a Channel Roll (15). On a success, project a hard-light morph, taking the shape of an inanimate object no larger than twice your normal size until you take damage.\nCorruption Code (was Eternal Enervation): Once per long rest, make a Channel Roll against a target within Close range. On a success, they become permanently Vulnerable and can't clear it by any means."),
    ("grid", "Deletion Wave", "Disintegration Wave", 9, "spell", 4,
     "Make a Channel Roll (18). Once per long rest on a success, the GM tells you which adversaries within Far range have Difficulty 18 or lower. Mark a Stress for each one you wish to hit. They are deleted from existence and can't come back by any means."),
    ("grid", "Archive of Yarrow", "Book of Yarrow", 10, "archive", 2,
     "Chrono Jam (was Timejammer): Make a Channel Roll (18). On a success, time temporarily slows to a halt for everyone within Far range except you until you make an action roll targeting another creature.\nNull Skin (was Magic Immunity): Spend 5 Signal to become immune to energy damage until your next rest."),
    ("grid", "Network Union", "Transcendent Union", 10, "spell", 1,
     "Once per long rest, spend 5 Signal to neural-link two or more willing creatures. Until your next rest, when a connected creature would mark Stress or Hit Points, the connected creatures can choose who marks it."),
    # SABLE
    ("sable", "Deft Deceiver", None, 1, "ability", 0,
     "Spend a Signal to gain advantage on a roll to deceive or trick someone into believing a lie you tell them."),
    ("sable", "Enrapture", None, 1, "spell", 0,
     "Make a Channel Roll against a target within Close range. On a success, they become temporarily Enraptured—their attention fixed on you. Once per rest on a success, you can mark a Stress to force the Enraptured target to mark a Stress as well."),
    ("sable", "Inspirational Words", None, 1, "ability", 1,
     "After a long rest, place tokens equal to your Presence on this card. When you speak with an ally, spend a token to let them clear a Stress, clear a Hit Point, or gain a Signal. Clear unspent tokens on a long rest."),
    ("sable", "Tell No Lies", None, 2, "spell", 1,
     "Make a Channel Roll against a target within Very Close range. On a success, they can't lie to you while within Close range but aren't compelled to speak. If they refuse to answer a question, they must mark a Stress and the effect ends."),
    ("sable", "Troublemaker", None, 2, "ability", 2,
     "When you taunt or provoke a target within Far range, make a Presence Roll against them. Once per rest on a success, roll d4s equal to your Proficiency. The target must mark Stress equal to the highest result."),
    ("sable", "Hypnotic Shimmer", None, 3, "spell", 1,
     "Make a Channel Roll against all adversaries in front of you within Close range. Once per rest on a success, create flashing lights that temporarily Stun targets you succeed against and force them to mark a Stress. While Stunned, they can't use reactions or take other actions until they clear the condition."),
    ("sable", "Invisibility", None, 3, "spell", 1,
     "Make a Channel Roll (10). On a success, mark a Stress and choose yourself or an ally within Melee range to become Invisible. Place tokens equal to your Channel trait on this card. When the Invisible creature takes an action, spend a token. After the last token is spent, the effect ends. You can only hold Invisibility on one creature at a time."),
    ("sable", "Soothing Speech", None, 4, "ability", 1,
     "During a short rest, when you Tend to Wounds on another character, clear an additional Hit Point on them and also clear 2 Hit Points on yourself."),
    ("sable", "Through Your Eyes", None, 4, "spell", 1,
     "Choose a target within Very Far range. You can see through their eyes and hear through their ears until you use another Channel ability or your next rest."),
    ("sable", "Thought Delver", None, 5, "spell", 2,
     "Spend a Signal to read vague surface thoughts of a target within Far range. Make a Channel Roll to delve for deeper thoughts. On a roll with Static, the target might become aware you're reading them."),
    ("sable", "Words of Discord", None, 5, "spell", 1,
     "Whisper words of discord to an adversary within Melee range and make a Channel Roll (13). On a success, the target must mark a Stress and attack another adversary instead of you or your allies. The next time you use this on them, gain −5 to the Channel Roll."),
    ("sable", "Never Upstaged", None, 6, "ability", 2,
     "When you mark 1 or more Hit Points from an attack, you can mark a Stress to place tokens equal to the Hit Points marked on this card. On your next successful attack, gain +5 to your damage roll per token, then clear all tokens."),
    ("sable", "Share the Burden", None, 6, "spell", 0,
     "Once per rest, take on Stress from a willing creature within Melee range. Transfer any number of their marked Stress to you, then gain a Signal for each Stress transferred."),
    ("sable", "Endless Charisma", None, 7, "ability", 2,
     "After you make an action roll to persuade, lie, or gain favor, you can spend a Signal to reroll the Signal or Static Die."),
    ("sable", "Sable-Touched", "Grace-Touched", 7, "ability", 2,
     "When 4 or more domain cards in your loadout are from Sable: you can mark an Armor Slot instead of marking a Stress; when you would force a target to mark Hit Points, you can choose to force them to mark that many Stress instead."),
    ("sable", "Ghost Signal", "Astral Projection", 8, "spell", 0,
     "Once per long rest, mark a Stress to broadcast a projected copy of yourself anywhere you've been before. You can see, hear, and affect the world as though you were there until your next rest or the projection takes damage."),
    ("sable", "Mass Enrapture", None, 8, "spell", 3,
     "Make a Channel Roll against all targets within Far range. Targets you succeed against become temporarily Enraptured. Mark a Stress to force all Enraptured targets to mark a Stress, ending this spell."),
    ("sable", "Copycat", None, 9, "spell", 3,
     "Once per long rest, mimic a level 8 or lower domain card from another player's loadout. Spend Signal equal to half the card's level to gain access until your next rest or they vault the card."),
    ("sable", "Master of the Craft", None, 9, "ability", 0,
     "Gain a permanent +2 bonus to two Experiences or a permanent +3 bonus to one Experience. Then place this card in your vault permanently."),
    ("sable", "Encore", None, 10, "spell", 1,
     "When an ally within Close range deals damage to an adversary, make a Channel Roll against that target. On a success, you deal the same damage your ally just dealt. On success with Static, place this card in your vault."),
    ("sable", "Notorious", None, 10, "ability", 0,
     "When you leverage your notoriety, mark a Stress before you roll to gain +10 to the result. Food and drinks are always free; everything else is reduced by one bag of credits (minimum a handful). This card doesn't count against your loadout maximum of 5 and can't be placed in your vault."),
    # SHADOW
    ("shadow", "Pick and Pull", None, 1, "ability", 0,
     "You have advantage on action rolls to pick standard locks, disarm standard traps, or steal items from a target."),
    ("shadow", "Rain of Blades", None, 1, "spell", 1,
     "Spend a Signal to make a Channel Roll and deploy razor flechettes at all targets within Very Close range. Targets you succeed against take d8+2 energy damage using your Proficiency. Vulnerable targets take an extra 1d8."),
    ("shadow", "Uncanny Disguise", None, 1, "spell", 0,
     "When you have a few minutes to prepare, mark a Stress to don the facade of any humanoid you can picture clearly. Place tokens equal to your Channel trait on this card. When you take an action while disguised, spend a token. After the last token is spent, the disguise drops."),
    ("shadow", "Shadow Specter", "Midnight Spirit", 2, "spell", 1,
     "Spend a Signal to project a shadow specter that can move or carry things until your next rest, or attack an adversary within Very Far range (Channel Roll; on success, deal d6s equal to your Channel trait in energy damage, then the specter dissipates). Only one specter at a time."),
    ("shadow", "Shadowbind", None, 2, "spell", 0,
     "Make a Channel Roll against all adversaries within Very Close range. Targets you succeed against are temporarily Restrained as shadow binds them."),
    ("shadow", "Chokehold", None, 3, "ability", 0,
     "When behind a creature about your size, mark a Stress to pull them into a chokehold, making them temporarily Vulnerable. Attacks against them deal an extra 2d6 damage."),
    ("shadow", "Veil of Night", None, 3, "spell", 1,
     "Make a Channel Roll (13). On a success, create a temporary curtain of darkness between two points within Far range. Only you can see through it. You're Hidden to adversaries on the other side and have advantage on attacks through the darkness until you use another Channel ability."),
    ("shadow", "Stealth Expertise", None, 4, "ability", 0,
     "When you fail with Static while moving unnoticed, mark a Stress to roll with Signal instead. You can do the same for an ally within Close range."),
    ("shadow", "Painted Target", "Glyph of Nightfall", 4, "spell", 1,
     "Make a Channel Roll against a target within Very Close range. On a success, spend a Signal to burn a vulnerability marker onto them, temporarily reducing their Difficulty by your Knowledge (minimum 1)."),
    ("shadow", "Hush", None, 5, "spell", 1,
     "Make a Channel Roll against a target within Close range. On a success, spend a Signal to project suppressive interference in Very Close range around them that follows them. The target and area are Silenced until cleared. While Silenced, they can't make noise or use Channel abilities."),
    ("shadow", "Phantom Retreat", None, 5, "spell", 2,
     "Spend a Signal to activate Phantom Retreat where you're standing. Spend another Signal before your next rest to disappear and reappear where you activated it."),
    ("shadow", "Dark Whispers", None, 6, "spell", 0,
     "Speak into the mind of anyone you've made physical contact with. Mark a Stress and make a Channel Roll to ask the GM: where are they, what are they doing, what are they afraid of, or what do they cherish most."),
    ("shadow", "Mass Disguise", None, 6, "spell", 0,
     "With a few minutes of silence, mark a Stress to disguise all willing creatures within Close range. Activate a Countdown (8); when it triggers, the disguise drops."),
    ("shadow", "Shadow-Touched", "Midnight-Touched", 7, "ability", 2,
     "When 4 or more domain cards are from Shadow: once per rest when you have 0 Signal and the GM would gain Static, gain a Signal instead; on a successful attack, mark a Stress to add your Static Die to damage."),
    ("shadow", "Vanishing Dodge", None, 7, "spell", 1,
     "When an attack that would deal physical damage fails against you, spend a Signal to become Hidden and teleport within Close range of the attacker. Remain Hidden until your next action roll."),
    ("shadow", "Shadowhunter", None, 8, "ability", 2,
     "While in low light or darkness, gain +1 Evasion and make attack rolls with advantage."),
    ("shadow", "Surge Cache", "Spellcharge", 8, "spell", 1,
     "When you take energy damage, place tokens equal to Hit Points marked (up to your Channel trait). On a successful attack, spend tokens to add a d6 per token to damage."),
    ("shadow", "Night Terror", None, 9, "spell", 2,
     "Once per long rest, targets within Very Close range must succeed on Reaction Roll (16) or become temporarily Horrified and Vulnerable. Steal Static from the GM equal to Horrified targets (up to the pool). Roll d6s equal to stolen Static and deal total damage to each Horrified target."),
    ("shadow", "Twilight Toll", None, 9, "ability", 1,
     "Choose a target within Far range. On successful non-damage action rolls against them, place a token. When you deal damage, spend tokens to add d12 per token. Only one target at a time."),
    ("shadow", "Eclipse", None, 10, "spell", 2,
     "Make a Channel Roll (16). Once per long rest on a success, plunge Far range into darkness only you and allies see through. Attacks against you or allies have disadvantage. When you or an ally succeeds with Signal against an adversary in the shadow, they mark a Stress. Lasts until the GM spends Static or you take Severe damage."),
    ("shadow", "Specter of the Dark", None, 10, "spell", 1,
     "Mark a Stress to become Spectral until you make an action roll targeting another creature. Immune to physical damage; can float and pass through solid objects."),
    # CIPHER
    ("cipher", "Gifted Tracker", None, 1, "ability", 0,
     "When tracking creatures, spend Signal to ask the GM questions (direction, how long ago, what they were doing, how many). When you encounter tracked creatures, gain +1 Evasion against them."),
    ("cipher", "Nature's Tongue", None, 1, "ability", 0,
     "Make an Instinct Roll (12) to communicate with or read alien creatures. Before a Channel Roll in a biological or xenological environment, spend a Signal for +2."),
    ("cipher", "Vicious Entangle", None, 1, "spell", 1,
     "Make a Channel Roll against a target within Far range. On a success, biotech tendrils deal 1d8+1 physical damage and temporarily Restrain them. Spend a Signal to Restrain another adversary within Very Close range."),
    ("cipher", "Conjure Swarm", None, 2, "spell", 1,
     "Swarm Drones: Mark a Stress to release micro-drones; when you next take damage, reduce severity by one threshold (spend Signal to keep active).\nScatter Drones: Channel Roll against all adversaries within Close range; spend a Signal to deal 2d8+3 energy damage to targets you succeed against."),
    ("cipher", "Natural Familiar", None, 2, "spell", 1,
     "Spend a Signal to summon a small xenoform companion until your next rest or it's attacked. Spend an additional Signal for a flying companion. Add d6 to damage against adversaries within Melee range of your familiar."),
    ("cipher", "Corrosive Projectile", None, 3, "spell", 1,
     "Make a Channel Roll against a target within Far range. On a success, deal d6+4 energy damage. Mark 2+ Stress to make them permanently Corroded (−1 Difficulty per 2 Stress spent; stacks)."),
    ("cipher", "Bio Spire", "Towering Stalk", 3, "spell", 1,
     "Once per rest, trigger rapid-growth biological formation within Close range (up to Far height). Mark a Stress to attack: Channel Roll against adversaries within Close range; on success, lift and drop them for d8 physical damage using your Proficiency."),
    ("cipher", "Death Grip", None, 4, "spell", 1,
     "Make a Channel Roll within Close range and choose: pull into Melee range; force 2 Stress; or adversaries between you and target take 3d6+2 physical on failed Reaction Roll (13). On success, Restrain the target."),
    ("cipher", "Healing Field", None, 4, "spell", 2,
     "Once per long rest, deploy a biomedical nanite field within Close range. You and allies clear a Hit Point (spend 2 Signal to clear 2 Hit Points instead)."),
    ("cipher", "Quill Hide", "Thorn Skin", 5, "spell", 1,
     "Once per rest, spend a Signal and place tokens equal to your Channel trait. When you take damage, spend tokens to roll d6s and reduce damage by the total; deal that damage back if within Melee range. Clear tokens on rest."),
    ("cipher", "Wild Fortress", None, 5, "spell", 1,
     "Make a Channel Roll (13). On a success, spend 2 Signal for a dome you and one ally can shelter in (can't attack or be targeted; attacks against the dome auto-succeed). Thresholds 15/30, lasts until 3 Hit Points marked on the card."),
    ("cipher", "Conjured Steeds", None, 6, "spell", 0,
     "Spend Signal to summon xenoform mounts until your next long rest or they take damage. Double land travel speed; move within Far range without rolling in danger. Riders: −2 attack, +2 damage."),
    ("cipher", "Forager", None, 6, "ability", 1,
     "As an additional downtime move, roll d6 to scavenge a consumable (ration, relic, calibration tool, medstim, lucky component, or choose). Party can carry up to five foraged consumables."),
    ("cipher", "Cipher-Touched", "Sage-Touched", 7, "ability", 2,
     "When 4+ Cipher cards in loadout: +2 Channel Rolls in biological, xenological, or constructed-systems environments; once per rest, double Agility or Instinct on a roll (before rolling)."),
    ("cipher", "Wild Surge", None, 7, "spell", 2,
     "Once per long rest, mark a Stress to enhance yourself. Place a d6 on this card (1 up). Add its value to every action roll; after each use, increase by 1. When it would exceed 6 or you rest, the form drops and you mark an additional Stress."),
    ("cipher", "Xeno Sprites", "Forest Sprites", 8, "spell", 2,
     "Make a Channel Roll (13). On a success, spend Signal to create constructs within Far range: allies gain +3 attack against adversaries near a construct; allies can mark an extra Armor Slot near a construct. Constructs vanish after granting a benefit or taking damage."),
    ("cipher", "Rejuvenation Barrier", None, 8, "spell", 1,
     "Make a Channel Roll (15). Once per rest on a success, barrier at Very Close range; allies inside when cast clear 1d4 Hit Points and have resistance to outside physical damage. Barrier follows you."),
    ("cipher", "Cipher Resonance", "Fane of the Wilds", 9, "ability", 2,
     "After a long rest, place tokens equal to Cipher cards in loadout and vault. Spend tokens after Channel Rolls for +1 per token. Gain a token on critical Cipher spell success. Clear on long rest."),
    ("cipher", "Bio Dominion", "Plant Dominion", 9, "spell", 1,
     "Make a Channel Roll (18). Once per long rest on a success, exert total control over the living biological environment within Far range."),
    ("cipher", "Force of Nature", None, 10, "spell", 2,
     "Mark a Stress to merge with a massive biotech construct: +10 damage on successful attack or Channel Roll; absorb defeated creatures within Close range to clear an Armor Slot; can't be Restrained. Spend a Signal before each action roll or revert."),
    ("cipher", "Tempest", None, 10, "spell", 2,
     "Choose Blizzard (2d20+8 energy, Vulnerable), Hurricane (3d10+10 energy, wind blocks movement), or Sandstorm (5d6+9 energy, ranged attacks at disadvantage). Channel Roll against all targets within Far range until GM spends Static."),
    # PSIONIC
    ("psionic", "Bolt Beacon", None, 1, "spell", 1,
     "Make a Channel Roll against a target within Far range. On a success, spend a Signal to deal d8+2 psionic damage using your Proficiency. The target becomes temporarily Vulnerable and is marked by visible psionic resonance."),
    ("psionic", "Mending Touch", None, 1, "spell", 1,
     "Spend 2 Signal to clear a Hit Point or Stress on a creature you focus on for a few minutes. Once per long rest, if you learn something new about them or reveal something about yourself, clear 2 Hit Points or 2 Stress instead."),
    ("psionic", "Reassurance", None, 1, "ability", 0,
     "Once per rest, after an ally attempts an action roll but before consequences, offer support so they can reroll their dice."),
    ("psionic", "Final Words", None, 2, "spell", 1,
     "Read lingering neural impressions of the recently deceased. Channel Roll (13). On success with Signal, answer up to three questions; with Static, one question. Impressions answer truthfully but only what the subject knew in life."),
    ("psionic", "Healing Hands", None, 2, "spell", 1,
     "Make a Channel Roll (13) targeting another creature within Melee range. On a success, mark a Stress to clear 2 Hit Points or 2 Stress; on failure, mark a Stress to clear one. Can't heal the same target again until your next long rest."),
    ("psionic", "Second Wind", None, 3, "ability", 2,
     "Once per rest, when you succeed on an attack, clear 3 Stress or a Hit Point. On success with Signal, also clear 3 Stress or a Hit Point on an ally within Close range."),
    ("psionic", "Voice of Reason", None, 3, "ability", 1,
     "Advantage on rolls to de-escalate violence or convince someone to follow your lead. When all Stress slots are marked, gain +1 Proficiency on damage rolls."),
    ("psionic", "Precognition", "Divination", 4, "spell", 1,
     "Once per long rest, spend 3 Signal to ask one yes-or-no question about the near future."),
    ("psionic", "Life Ward", None, 4, "spell", 1,
     "Spend 3 Signal and mark an ally within Close range with a psionic sigil. When they would make a death move, they clear a Hit Point instead. Ends when it saves them, you mark another target, or you take a long rest."),
    ("psionic", "Shape Material", None, 5, "spell", 1,
     "Spend a Signal to telekinetically shape material you're touching (stone, ice, metal, polymer) within Close range, no larger than you—for tools, doors, etc."),
    ("psionic", "Mind Strike", "Smite", 5, "spell", 2,
     "Once per rest, spend 3 Signal to charge a psionic strike. On your next successful weapon attack, double your damage roll. The attack deals psionic damage regardless of weapon type."),
    ("psionic", "Restoration", None, 6, "spell", 2,
     "After a long rest, place tokens equal to your Channel trait. Touch a creature and spend tokens to clear 2 Hit Points or 2 Stress per token, or clear Vulnerable/repair ailments (GM may require extra tokens)."),
    ("psionic", "Zone of Protection", None, 6, "spell", 2,
     "Make a Channel Roll (16). Once per long rest on a success, create a protection zone within Far range. Place a d6 (1 up) on this card; allies in the zone reduce damage by the die's value, then increase the die. Ends when the die would exceed 6."),
    ("psionic", "Healing Strike", None, 7, "spell", 1,
     "When you deal damage to an adversary, spend 2 Signal to clear a Hit Point on an ally within Close range."),
    ("psionic", "Psionic-Touched", "Splendor-Touched", 7, "ability", 2,
     "When 4+ Psionic cards in loadout: +3 Severe damage threshold; once per long rest, when incoming damage would mark Hit Points, mark that much Stress or spend that much Signal instead."),
    ("psionic", "Shield Aura", None, 8, "spell", 2,
     "Mark a Stress to cast on a target within Very Close range. When they mark an Armor Slot, reduce attack severity by an additional threshold. Ends if they mark no Hit Points from an attack. Only one target at a time."),
    ("psionic", "Stunning Radiance", "Stunning Sunlight", 8, "spell", 2,
     "Channel Roll against adversaries in front of you within Far range. On a success, spend Signal to force targets to Reaction Roll (14). Fail: 4d20+5 psionic damage and Stunned. Succeed: 3d20+3 psionic damage."),
    ("psionic", "Overwhelming Aura", None, 9, "spell", 2,
     "Make a Channel Roll (15). On a success, spend 2 Signal to make your Presence equal to your Channel trait until your next long rest. Adversaries must mark a Stress when they target you with an attack."),
    ("psionic", "Salvation Beam", None, 9, "spell", 2,
     "Make a Channel Roll (16). On a success, mark Stress to clear Hit Points on allies in a line within Far range, divided however you like."),
    ("psionic", "Invigoration", None, 10, "spell", 3,
     "When you or an ally within Close range has used a once-per-rest or once-per-session feature, spend Signal and roll d6s. On any 6, the feature can be used again."),
    ("psionic", "Resurrection", None, 10, "spell", 2,
     "Make a Channel Roll (20). On a success, restore a creature dead no longer than 100 years. Roll d6; on 5 or lower, vault this card permanently. On failure, can't cast Resurrection again for a week."),
    # TIDE
    ("tide", "Bare Bones", None, 1, "ability", 0,
     "When you choose not to equip armor, base Armor Score is 3 + Strength and damage thresholds: Tier 1: 9/19; Tier 2: 11/24; Tier 3: 13/31; Tier 4: 15/38."),
    ("tide", "Forceful Push", None, 1, "ability", 0,
     "Attack with primary weapon within Melee range. On success, deal damage and knock to Close range. On success with Signal, add d6 damage. Spend a Signal to make them temporarily Vulnerable."),
    ("tide", "I Am Your Shield", None, 1, "ability", 1,
     "When an ally within Very Close range would take damage, mark a Stress to become the target instead. You can mark any number of Armor Slots when taking that damage."),
    ("tide", "Body Basher", None, 2, "ability", 1,
     "On a successful Melee weapon attack, gain a bonus to damage equal to your Strength."),
    ("tide", "Bold Presence", None, 2, "ability", 0,
     "When you make a Presence Roll, spend a Signal to add your Strength. Once per rest when you would gain a condition, describe how your bold presence helps and avoid the condition."),
    ("tide", "Critical Inspiration", None, 3, "ability", 1,
     "Once per rest, when you critically succeed on an attack, all allies within Very Close range can clear a Stress or gain a Signal."),
    ("tide", "Lean On Me", None, 3, "ability", 1,
     "Once per long rest, when you console or inspire an ally who failed an action roll, you both clear 2 Stress."),
    ("tide", "Goad Them On", None, 4, "ability", 1,
     "Presence Roll against a target within Close range. On a success, they mark a Stress and must target you with their next attack (with disadvantage)."),
    ("tide", "Support Tank", None, 4, "ability", 2,
     "When an ally within Close range fails a roll, spend 2 Signal to let them reroll their Signal or Static Die."),
    ("tide", "Armorer", None, 5, "ability", 1,
     "While wearing armor, gain +1 Armor Score. During a rest when you repair armor, allies also clear an Armor Slot."),
    ("tide", "Rousing Strike", None, 5, "ability", 1,
     "Once per rest, when you critically succeed on an attack, you and allies who can see or hear you clear a Hit Point or 1d4 Stress."),
    ("tide", "Inevitable", None, 6, "ability", 1,
     "When you fail an action roll, your next action roll has advantage."),
    ("tide", "Rise Up", None, 6, "ability", 2,
     "Gain a bonus to your Severe threshold equal to your Proficiency. When you mark 1 or more Hit Points from an attack, clear a Stress."),
    ("tide", "Shrug It Off", None, 7, "ability", 1,
     "When you would take damage, mark a Stress to reduce severity by one threshold. Roll d6; on 3 or lower, place this card in your vault."),
    ("tide", "Tide-Touched", "Valor-Touched", 7, "ability", 1,
     "When 4+ Tide cards in loadout: +1 Armor Score; when you mark Hit Points without marking an Armor Slot, clear an Armor Slot."),
    ("tide", "Full Surge", None, 8, "ability", 1,
     "Once per long rest, mark 3 Stress for +2 to all character traits until your next rest."),
    ("tide", "Ground Pound", None, 8, "ability", 2,
     "Spend 2 Signal to strike the ground. Strength Roll against all targets within Very Close range. On success, throw them to Far range; Reaction Roll (17)—fail: 4d10+8 damage, succeed: half."),
    ("tide", "Hold the Line", None, 9, "ability", 1,
     "Spend a Signal. Adversaries who move within Very Close range are pulled into Melee and Restrained until you move, fail with Static, or the GM spends 2 Static."),
    ("tide", "Lead by Example", None, 9, "ability", 3,
     "When you deal damage, mark a Stress and describe how you encourage allies. The next PC to attack that adversary can clear a Stress or gain a Signal."),
    ("tide", "Unbreakable", None, 10, "ability", 4,
     "When you mark your last Hit Point, instead of a death move, roll d6 and clear that many Hit Points, then vault this card."),
    ("tide", "Unyielding Armor", None, 10, "ability", 1,
     "When you would mark an Armor Slot, roll d6s equal to your Proficiency. On any 6, reduce severity by one threshold without marking an Armor Slot."),
]


def slugify(domain: str, name: str) -> str:
    slug = name.lower().replace(" ", "-").replace("'", "")
    return f"{domain}-{slug}"


def main():
    cards = []
    for domain, name, was, level, ctype, recall, effect in CARDS:
        cards.append({
            "id": slugify(domain, name),
            "domain": domain,
            "name": name,
            "was": was,
            "level": level,
            "type": ctype,
            "recallCost": recall,
            "effect": effect,
        })

    payload = {"domains": DOMAINS, "cards": cards}
    out = ROOT / "data" / "domain-cards.json"
    out.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    # Also emit JS for file:// compatibility
    js_out = ROOT / "data" / "domain-cards-data.js"
    js_out.write_text(
        "// Auto-generated by scripts/build-domain-cards.py — do not edit by hand\n"
        f"window.VOIDHEART_DOMAIN_CARDS = {json.dumps(payload, ensure_ascii=False)};\n",
        encoding="utf-8",
    )
    print(f"Wrote {len(cards)} cards to {out} and {js_out}")


if __name__ == "__main__":
    main()

